"""
Example: Basic usage of the Anticipation Layer.

This demonstrates how an AI agent can use the Anticipation Layer
to maintain temporal awareness across interactions.
"""

import asyncio
from anticipation_layer import AnticipationLayer, Horizon, Category, Impact


async def main():
    # ── Initialize the layer ──────────────────────────────────────
    layer = AnticipationLayer(storage_dir="./my_anticipations")

    # ── Manually add some anticipations ───────────────────────────
    # In a real system, these would be generated by an LLM

    layer.add(
        prediction="Thursday's deployment may fail if hotfix #342 is not merged by Wednesday.",
        horizon=Horizon.SHORT_TERM,
        category=Category.RISK,
        impact=Impact.HIGH,
        confidence=0.75,
        domain="project-alpha",
        suggested_actions=[
            "Follow up with backend team on hotfix #342",
            "Prepare a rollback plan",
        ],
    )

    layer.add(
        prediction="Sprint review should go smoothly — all items are completed.",
        horizon=Horizon.SHORT_TERM,
        category=Category.OPPORTUNITY,
        impact=Impact.MEDIUM,
        confidence=0.85,
        domain="project-alpha",
    )

    layer.add(
        prediction="Q2 budget will likely be exceeded by 15% at current spending rate.",
        horizon=Horizon.MEDIUM_TERM,
        category=Category.RISK,
        impact=Impact.HIGH,
        confidence=0.60,
        domain="finance",
        suggested_actions=[
            "Review discretionary spending",
            "Schedule budget review with CFO",
        ],
    )

    layer.add(
        prediction="New competitor product launch in September could erode 10% market share.",
        horizon=Horizon.LONG_TERM,
        category=Category.RISK,
        impact=Impact.CRITICAL,
        confidence=0.40,
        domain="strategy",
        suggested_actions=[
            "Accelerate feature roadmap for Q3",
            "Commission competitive analysis",
        ],
    )

    # ── Check status ──────────────────────────────────────────────
    print("=" * 60)
    print("CURRENT ANTICIPATIONS")
    print("=" * 60)
    print(layer.status())

    # ── Get context for a specific query ──────────────────────────
    print("=" * 60)
    print("CONTEXT FOR: 'Should we deploy on Thursday?'")
    print("=" * 60)
    context = layer.get_context("Should we deploy on Thursday?")
    print(context)

    # ── Register an event (triggers invalidation check) ───────────
    print("=" * 60)
    print("EVENT: Hotfix #342 was merged successfully")
    print("=" * 60)
    invalidated = layer.register_event("Hotfix #342 was merged successfully and deployed to staging.")
    if invalidated:
        print(f"Invalidated {len(invalidated)} anticipation(s):")
        for ant in invalidated:
            print(f"  - {ant.id}: {ant.prediction[:60]}...")
    else:
        print("No anticipations invalidated.")

    # ── Get updated context ───────────────────────────────────────
    print("\n" + "=" * 60)
    print("UPDATED CONTEXT FOR: 'Should we deploy on Thursday?'")
    print("=" * 60)
    context = layer.get_context("Should we deploy on Thursday?")
    print(context)

    # ── Run consolidation ─────────────────────────────────────────
    print("=" * 60)
    print("RUNNING CONSOLIDATION (idle cycle)")
    print("=" * 60)
    summary = await layer.consolidate(
        current_context="Sprint ends Friday. Team at full capacity. Q2 halfway through."
    )
    print(f"Consolidation results: {summary}")

    # ── Check metrics ─────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("METRICS")
    print("=" * 60)
    metrics = layer.metrics()
    for key, value in metrics.items():
        print(f"  {key}: {value}")


if __name__ == "__main__":
    asyncio.run(main())
